language: julia
sudo: false
dist: trusty
os:
  - linux
julia:
  - 1.5
  - nightly
notifications:
  email: false

# comment the following lines to disallow failures on nightly julia
matrix:
  allow_failures:
  - julia: nightly

codecov: true

script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; 
                                                      Pkg.instantiate(); 
                                                      Pkg.build();
                                                      Pkg.test(coverage=true);'

  - sudo apt-get update
  - sudo apt-get -qq install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5 xvfb
  - export DOCUMENTER_DEBUG="true"
  - julia --project=docs/ --color=yes -e 'using Pkg;
                                          Pkg.develop(PackageSpec(path=pwd())); 
                                          Pkg.instantiate(); 
                                          Pkg.build("Insolation")'
  - julia --project=docs/ --color=yes 'docs/make.jl'

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg;
              cd(Pkg.dir("Insolation"));
              Pkg.add("Coverage");
              using Coverage;
              Codecov.submit(Codecov.process_folder())'
