status = [
  "ci 1.5.4 - ubuntu-latest",
  "ci 1.5.4 - windows-latest",
  "ci 1.5.4 - macOS-latest",
  "docbuild",
]
delete_merged_branches = true
timeout_sec = 3600
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
